services:
  webserver:
    build: ./webserver
    ports:
      - "80:80"
      - "8080:8080"
      - "2222:22"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/KEO_SIENGHENG-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Hello@123

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=KEO_SIENGHENG-db
      - MYSQL_ROOT_PASSWORD=Hello@123
    volumes:
      - db_data:/var/lib/mysql

  loadbalancer:
    build: ./webserver
    ports:
      - "8090:80"
      - "2223:22"
    depends_on:
      - db
      - webserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/KEO_SIENGHENG-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Hello@123

volumes:
  db_data: